# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ec1c15d54b34e60a9dbdc3a0e5369197c5d09d353e7fc193c70b3f18645980f557e6ba93537caf135380d53ebd576a60a3988499b010cc9e4fa1189a4380f71

test:
  secret_key_base: e2caeb9d5818393a4d258bea5ded30e8fc8095b7ab325c821611c839a727d5022dc9c4caa0088853d03e1ef03d0cb65ad2a20a7ddfd5420c30967a355c412cb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
